### ISSUE TITLE
Run using pre-commit

### ISSUE THREAD

**Issue by martimors** [bitnami/readme-generator-for-helm#45]
Following the completion of https://github.com/bitnami-labs/readme-generator-for-helm/issues/36, it could be nice to be able to run the generator as a [pre-commit](https://pre-commit.com/) hook. That would significantly simplify running this tool in a CI context, as well as helping chart contributors document configuration options correctly.

I can potentially contribute to this depending on my schedule, but if anyone else wants to do it please feel free. It should be as straight forward as adding a single file to the root of the repo (I think...).

**Comment by miguelaeh** [comment]
Thanks for the suggestion @dingobar . Please feel free to contribute with such a feature.

It was not added before because it requires every developer to install the hooks locally. For example, in the case you use GitHub for the charts, configuring a GitHub action to run the generator will enforce the execution on every Chart PR without requiring the developers to install the hooks.

**Comment by dingobar** [comment]
1 year later, I randomly stumbled upon my issue again, as the need arose again for generating docs, and I don't want to have to manually install a tool to do this when it could easily just install itself using `pre-commit`.

I don't understand the explanation given above. Why is it a bad thing to install pre-commit hooks locally? Isn't this the whole point of them? The hook should generate the readme, that is then committed by the dev. If the CI pipeline makes changes to the readme, it should fail.
